# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b730e25d8341ff47cfc4f39164d7203a"
name = "synergistic-sponsorship-app"
handle = "synergistic-sponsorship-app-5"
application_url = "https://ted-methods-trinity-fraction.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-build-env.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ted-methods-trinity-fraction.trycloudflare.com/auth/callback",
  "https://ted-methods-trinity-fraction.trycloudflare.com/auth/shopify/callback",
  "https://ted-methods-trinity-fraction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
